### ISSUE TITLE
The attribute body does not exist on the node--apidoc resource type

### ISSUE THREAD

**Issue by subbapotla** [apigee/apigee-api-catalog-drupal#100]
**Describe the bug**
Creation of API Doc failed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Version Info**
Drupal 8.9.3
Apigee Edge 8.x-1.13
Apigee API Catalog 8.x-2.3
JSON:API Extras 8.x-3.15

Error : 
2020-08-10 16:52:35 INFO  APIDocsMojo:64 - ************************************************************************
2020-08-10 16:52:35 INFO  APIDocsMojo:65 - API Docs
2020-08-10 16:52:35 INFO  APIDocsMojo:66 - ************************************************************************
2020-08-10 16:52:35 INFO  APIDocsMojo:207 - Get OpenAPI Specs from ./specs
2020-08-10 16:52:35 INFO  PortalRestUtil:508 - Getting API doc for High Loan to Value Data API
2020-08-10 16:52:35 INFO  PortalRestUtil:514 - Retrieving High Loan to Value Data API doc.
2020-08-10 16:52:35 INFO  PortalRestUtil:524 - API Doc: High Loan to Value Data API does not exist
2020-08-10 16:52:35 INFO  PortalRestUtil:541 - Importing spec..
2020-08-10 16:52:35 INFO  PortalRestUtil:552 - Spec import complete..
2020-08-10 16:52:35 INFO  PortalRestUtil:557 - File uuid:a60d350b-e427-485a-8679-16cee5c88469
2020-08-10 16:52:35 INFO  PortalRestUtil:609 - Creating spec..a60d350b-e427-485a-8679-16cee5c88469
2020-08-10 16:52:35 INFO  PortalRestUtil:469 - Retrieving taxonomy_term for api_type
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.126s
[INFO] Finished at: Mon Aug 10 16:52:36 EDT 2020
[INFO] Final Memory: 15M/360M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.1.0:apidoc (smartdocs-deploy) on project DeveloperPortal: Execution smartdocs-deploy of goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.1.0:apidoc failed: Update failure:
[ERROR] Status code: 422
[ERROR] Status Message: Unprocessable Entity
[ERROR] Detailed Message: The attribute body does not exist on the node--apidoc resource type.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.1.0:apidoc (smartdocs-deploy) on project DeveloperPortal: Execution smartdocs-deploy of goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.1.0:apidoc failed: Update failure: 
Status code: 422
Status Message: Unprocessable Entity
Detailed Message: The attribute body does not exist on the node--apidoc resource type.

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution smartdocs-deploy of goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.1.0:apidoc failed: Update failure: 
Status code: 422
Status Message: Unprocessable Entity
Detailed Message: The attribute body does not exist on the node--apidoc resource type.

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.RuntimeException: Update failure: 
Status code: 422
Status Message: Unprocessable Entity
Detailed Message: The attribute body does not exist on the node--apidoc resource type.

	at com.apigee.smartdocs.config.mavenplugin.APIDocsMojo.doUpdate(APIDocsMojo.java:173)
	at com.apigee.smartdocs.config.mavenplugin.APIDocsMojo.execute(APIDocsMojo.java:142)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by subbapotla** [comment]
I found that the payload is is having status attribute which is having value of true. Administrator access is required to update the status. 

aAnother finding is if I remove body from  attributes payload, it is working as expected. So something with this body attribute is having issue.

         "body":{
            "value":"some description",
            "format":"basic_html"
         },

**Comment by arlina-espinoza** [comment]
@subbapotla You can try verifying the following two things:
- That a text format named "basic_html" actually exists on your site ( _/admin/config/content/formats_)
- That the user that you are using to connect through the REST endpoint has a role with permission to use that text format (_/admin/config/content/formats/manage/basic_html)_

**Comment by subbapotla** [comment]
Please find the attached screenshots.
[
<img width="703" alt="Screen Shot 2020-08-11 at 3 15 52 PM" src="https://user-images.githubusercontent.com/30415084/89944616-be9a5300-dbe5-11ea-8829-1562e8854fef.png">
<img width="1445" alt="Screen Shot 2020-08-11 at 3 12 16 PM" src="https://user-images.githubusercontent.com/30415084/89944636-c2c67080-dbe5-11ea-9362-054c20af860d.png">

](url)

**Comment by subbapotla** [comment]
I am seeing this error in Drupal recent log messages.

Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException: The attribute body does not exist on the node--apidoc resource type. in Drupal\jsonapi\Normalizer\FieldableEntityDenormalizer->prepareInput() (line 62 of /mnt/www/html/fnmaclvedevportaldeveng/docroot/core/modules/jsonapi/src/Normalizer/FieldableEntityDenormalizer.php).

**Comment by arlina-espinoza** [comment]
@subbapotla Could you post a screenshot of the fields configuration screen at _/admin/structure/types/manage/apidoc/fields_. Thanks!

**Comment by subbapotla** [comment]
Find the attached screenshot.
![node--apidoc](https://user-images.githubusercontent.com/30415084/90135380-2f518480-dd38-11ea-9b1e-a19b0d12758a.jpg)

**Comment by arlina-espinoza** [comment]
@subbapotla Could you post a screenshot/pdf of the `node--apidoc` resource type at `/admin/config/services/jsonapi/resource_types/node--apidoc/edit`, please? I'd like to make sure the "body" field isn't disabled or has different alias.

**Comment by arlina-espinoza** [comment]
Closing, feel free to reopen if more follow up is needed.
